"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Off unless explicitly switched on, so a missing or typo'd env var fails safe.
# docker-compose sets DEBUG=1 for local dev; Railway sets it per service.
# This matters more since /scarves/game/ went public: with DEBUG on, an
# unhandled exception renders settings and env vars (Square token, S3 keys,
# SECRET_KEY) to anonymous visitors.
DEBUG = os.environ.get("DEBUG", "").lower() in ("1", "true", "yes")

# SECURITY WARNING: keep the secret key used in production secret!
# The old key was committed to git, so it must be treated as public. Rotating
# it signs everyone out (sessions are signed with it) but does NOT affect
# stored passwords, which are hashed independently.
#
# No production fallback on purpose: if DJANGO_SECRET_KEY is missing the app
# refuses to boot rather than quietly running on a known-public key. Dev keeps
# a throwaway default so nothing extra is needed to run locally.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is not set. Refusing to start with DEBUG off "
            "rather than fall back to a key that is public in git history."
        )
    SECRET_KEY = "django-insecure-dev-only-not-for-deployment"

ALLOWED_HOSTS = ["*"]
# Django default: auto-redirect a slashless URL (e.g. /reference-sheet/11) to
# its slashed route (/reference-sheet/11/) when only the latter matches. Only
# affects GETs; POSTs aren't redirected (the Square webhook registers both
# forms explicitly in urls.py, so it's unaffected).
APPEND_SLASH = True

# FORM SUBMISSION
# Comment out the following line and place your railway URL, and your production URL in the array.
CSRF_TRUSTED_ORIGINS = [
    "https://server-production-ead0.up.railway.app",
    "https://server-development-d24f.up.railway.app",
]

# Application definition

INSTALLED_APPS = [
    "scarves.apps.ScarvesConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colorfield',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ["PGDATABASE"],
        'USER': os.environ["PGUSER"],
        'PASSWORD': os.environ["PGPASSWORD"],
        'HOST': os.environ["PGHOST"],
        'PORT': os.environ["PGPORT"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media / file storage
# ---------------------
# User-uploaded files (e.g. product images) use Django's `default` storage.
# The backend is chosen at startup by env vars: if the Railway S3 bucket vars
# are present we use django-storages' S3 backend; otherwise we fall back to the
# local filesystem so local dev needs no cloud creds. Railway's bucket is
# S3-compatible, so this is the standard boto3/S3 backend pointed at Railway's
# endpoint URL — swapping to real AWS S3 (or anything else) later is env-only.
# Variable names match Railway's automated django-storages integration, which
# injects them as reference values (${{Images.*}}) from the bucket service.
S3_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL", "")
S3_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
S3_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")

USE_S3 = bool(S3_BUCKET_NAME and S3_ENDPOINT_URL and S3_ACCESS_KEY_ID)

if USE_S3:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": S3_BUCKET_NAME,
                "endpoint_url": S3_ENDPOINT_URL,
                "access_key": S3_ACCESS_KEY_ID,
                "secret_key": S3_SECRET_ACCESS_KEY,
                "region_name": os.environ.get("AWS_S3_REGION_NAME", "auto"),
                # Signed URLs work regardless of bucket ACL support. If you make
                # the bucket public-read, set querystring_auth=False for stable,
                # cacheable URLs.
                "querystring_auth": True,
                "file_overwrite": False,
                # Railway/MinIO-style S3 needs path-style addressing, not the
                # virtual-hosted (bucket.endpoint) style AWS uses.
                "addressing_style": "path",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = "media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SQUARE_ACCESS_TOKEN = os.environ.get("SQUARE_ACCESS_TOKEN", "")
SQUARE_LOCATION_ID = os.environ.get("SQUARE_LOCATION_ID", "")
SQUARE_ENVIRONMENT = os.environ.get("SQUARE_ENVIRONMENT", "sandbox")
SQUARE_WEBHOOK_SIGNATURE_KEY = os.environ.get("SQUARE_WEBHOOK_SIGNATURE_KEY", "")
SQUARE_WEBHOOK_URL = os.environ.get("SQUARE_WEBHOOK_URL", "")

# settings.py
LOGIN_REDIRECT_URL = '/accounts/'