# Generated by Django 5.0.6 on 2025-11-24 03:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DyeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer-facing name, e.g. 'Stormy Sea Silk Scarf'.", max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price of the finished item.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_on_hand', models.PositiveIntegerField(default=0, help_text='How many finished items of this kind you have.')),
                ('sku', models.CharField(blank=True, help_text='SKU/code for the finished product.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost per unit of this raw product.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_url', models.URLField(blank=True, help_text='Where you buy this from (supplier URL).')),
                ('number_on_hand', models.PositiveIntegerField(default=0, help_text='How many undyed units you currently have.')),
                ('sku', models.CharField(blank=True, help_text="Your internal SKU or supplier's item number.", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if you no longer use this raw product.')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RawProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Raw product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_color', models.CharField(help_text='Hex color, e.g. #ffcc00', max_length=7)),
                ('in_stock', models.BooleanField(default=True)),
                ('sku', models.CharField(blank=True, help_text='Manufacturer or internal SKU', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dyes', to='scarves.dyebrand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='FinishedProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, help_text='Alt text / description for accessibility.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Ordering of images in galleries.')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scarves.finishedproduct')),
            ],
            options={
                'ordering': ['finished_product', 'order'],
            },
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='raw_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='scarves.rawproduct'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_products', to='scarves.rawproductcategory'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='scarves.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeDye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Order in which this dye appears in the recipe.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Optional proportion (e.g. grams, % of total).', max_digits=5, null=True)),
                ('dye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_dyes', to='scarves.dye')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_dyes', to='scarves.recipe')),
            ],
            options={
                'ordering': ['recipe', 'order'],
                'unique_together': {('recipe', 'dye')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='dyes',
            field=models.ManyToManyField(related_name='recipes', through='scarves.RecipeDye', to='scarves.dye'),
        ),
        migrations.AlterUniqueTogether(
            name='finishedproduct',
            unique_together={('raw_product', 'recipe', 'name')},
        ),
    ]
