# Generated by Django 5.0.6 on 2025-11-24 04:30

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='is_fancy',
            field=models.BooleanField(default=False, help_text='Mark as fancy to distinguish premium designs.'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested retail price for finished items made from this raw product.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dye',
            name='hex_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
