# Generated by Django 5.0.6 on 2025-11-27 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0002_finishedproduct_is_fancy_rawproduct_suggested_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='par',
            field=models.PositiveIntegerField(default=8, help_text='How many finished items of this kind you expect to have.'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='number_per_dye_bath',
            field=models.PositiveIntegerField(default=4, help_text='How many of this raw item you normally dye in one bath.'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Your cost for this raw product.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
