# Generated by Django 5.0.6 on 2025-11-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0003_finishedproduct_par_rawproduct_number_per_dye_bath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of finished items added (and raw units consumed).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='scarves.finishedproduct')),
                ('raw_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='scarves.rawproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
