# Generated by Django 5.0.6 on 2025-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0004_productionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='par_level',
            field=models.PositiveIntegerField(default=100, help_text='Target undyed quantity to keep on hand. 0 = no par set.'),
        ),
    ]
