# Generated by Django 5.0.6 on 2026-04-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0005_rawproduct_par_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='square_variation_id',
            field=models.CharField(blank=True, help_text='Square CatalogItemVariation ID for this finished product.', max_length=100),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='square_item_id',
            field=models.CharField(blank=True, help_text='Square CatalogItem ID for this product.', max_length=100),
        ),
    ]
