# Generated by Django 5.0.6 on 2026-04-19 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0006_finishedproduct_square_variation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('production', 'Production'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], default='production', max_length=20)),
                ('quantity', models.IntegerField(help_text='Items added (positive) or removed (negative).')),
                ('sale_reference', models.CharField(blank=True, help_text='Square order ID for sale entries.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='scarves.finishedproduct')),
                ('raw_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='scarves.rawproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductionLog',
        ),
    ]
