# Generated by Django 5.0.6 on 2026-08-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0009_rawproductcategory_square_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='date_precision',
            field=models.CharField(choices=[('exact', 'Exact time'), ('day', 'Day only'), ('month', 'Month only')], default='exact', help_text='How much of created_at is real. Back-filled entries from the old kanban cards often record only a month — this stops the app displaying a day nobody ever wrote down.', max_length=10),
        ),
    ]
