# Generated by Django 5.0.6 on 2026-08-06 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0010_inventorylog_date_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bands_confirmed_at',
            field=models.DateTimeField(blank=True, help_text="When a person last confirmed the bands above. Null means nothing has been confirmed yet, so the sheet must not print this recipe: an unchecked guess that files a scarf under the wrong color is worse than leaving it off, because the failure is silent — you look in orange, it isn't there, and nothing says why.", null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='color_bands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('neutral', 'Neutral')], max_length=12), blank=True, default=list, help_text='Which sections of the rainbow reference sheet this colorway is printed in. A red-and-orange scarf claims both and prints twice.', size=None),
        ),
    ]
