# Generated by Django 5.0.6 on 2026-08-06 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


def neutral_to_grey(apps, schema_editor):
    """Rehome the old `neutral` band, and send those rows back for review.

    `neutral` covered both grey and black, so a stored `neutral` doesn't say
    which section the scarf belongs in. Grey is the safer landing spot — it is
    the catch-all family now — but a genuinely black scarf filed under grey is
    exactly the silent miss this app refuses to print: you look in black, it
    isn't there, and nothing tells you why. So the confirmation is dropped too.
    The row keeps its bands as a starting point and stays off the sheet until a
    person says which one it is.
    """
    Recipe = apps.get_model('scarves', 'Recipe')
    for recipe in Recipe.objects.filter(color_bands__contains=['neutral']):
        recipe.color_bands = [
            'grey' if b == 'neutral' else b for b in recipe.color_bands
        ]
        recipe.bands_confirmed_at = None
        recipe.save(update_fields=['color_bands', 'bands_confirmed_at'])


def grey_to_neutral(apps, schema_editor):
    Recipe = apps.get_model('scarves', 'Recipe')
    for recipe in Recipe.objects.filter(color_bands__overlap=['grey', 'black']):
        recipe.color_bands = sorted(
            {'neutral' if b in ('grey', 'black') else b for b in recipe.color_bands}
        )
        recipe.save(update_fields=['color_bands'])


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0011_recipe_bands_confirmed_at_recipe_color_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='finished_par_default',
            field=models.PositiveIntegerField(default=8, help_text="Par given to a new finished product made from this blank. Only applies at creation — changing it never rewrites the par of a product that already exists, because that would silently re-schedule production. Use the raw-product admin action 'Bulk update finished product par' to change existing ones."),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='color_bands',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('black', 'Black')], max_length=12), blank=True, default=list, help_text='Which sections of the rainbow reference sheet this colorway is printed in. A red-and-orange scarf claims both and prints twice.', size=None),
        ),
        migrations.RunPython(neutral_to_grey, grey_to_neutral),
    ]
