# Generated by Django 5.0.6 on 2026-08-07 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0012_rawproduct_finished_par_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pin', models.CharField(help_text='Four digits, handed to the employee. Stored as typed so it can be read back to whoever forgets theirs — it guards a timesheet entry a person reviews, not an account.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'The PIN must be exactly four digits.')])),
                ('is_active', models.BooleanField(default=True, help_text='Unticked takes them off the hours form without touching the hours they already reported.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='The day worked — not the day it was reported.')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('16'))])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='scarves.employee')),
            ],
            options={
                'verbose_name_plural': 'time entries',
                'ordering': ['-work_date', 'employee__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='one_time_entry_per_employee_per_day'),
        ),
    ]
