# Generated by Django 5.0.6 on 2026-08-16 03:00

from decimal import Decimal
from django.db import migrations, models


# The one stock we buy, transcribed from the vendor's own spec page. Sold as
# OnlineLabels OL25WX, Avery 5167 and Uline S-16988 — same die, so the numbers
# below cover all three. 1.75in is what makes the barcode readable: a 14-char
# SKU lands around 7.3 mil here, where the 1in stock we nearly bought would
# have printed 4.5 mil and scanned unreliably.
#
# Sanity: 0.32812 + 3(2.03125) + 1.75 = 8.17 <= 8.5, and
#         0.5 + 19(0.5) + 0.5 = 10.5 <= 11. LabelStockTests re-checks this.
OL25WX = {
    "name": "Avery 5167 / OnlineLabels OL25WX — 1.75 x 0.5in, 80/sheet",
    # Staples carries the Avery-branded version of this die, which is where
    # the sheets get bought and printed. Same geometry either way.
    "purchase_url": (
        "https://www.staples.com/avery-easy-peel-laser-return-address-labels"
        "-1-2-x-1-3-4-white-80-labels-sheet-100-sheets-pack-5167/product_771972"
    ),
    "page_width_in": Decimal("8.5"),
    "page_height_in": Decimal("11"),
    "label_width_in": Decimal("1.75"),
    "label_height_in": Decimal("0.5"),
    "columns": 4,
    "rows": 20,
    "margin_left_in": Decimal("0.32812"),
    "margin_top_in": Decimal("0.5"),
    "pitch_x_in": Decimal("2.03125"),
    "pitch_y_in": Decimal("0.5"),
}


def seed_stocks(apps, schema_editor):
    LabelStock = apps.get_model("scarves", "LabelStock")
    LabelStock.objects.get_or_create(name=OL25WX["name"], defaults=OL25WX)


def unseed_stocks(apps, schema_editor):
    LabelStock = apps.get_model("scarves", "LabelStock")
    LabelStock.objects.filter(name=OL25WX["name"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0013_employee_timeentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('purchase_url', models.URLField(blank=True, help_text='Where to buy more of this stock. Shown on the label page.')),
                ('page_width_in', models.DecimalField(decimal_places=4, default=Decimal('8.5'), max_digits=6)),
                ('page_height_in', models.DecimalField(decimal_places=4, default=Decimal('11'), max_digits=6)),
                ('label_width_in', models.DecimalField(decimal_places=4, max_digits=6)),
                ('label_height_in', models.DecimalField(decimal_places=4, max_digits=6)),
                ('columns', models.PositiveSmallIntegerField()),
                ('rows', models.PositiveSmallIntegerField()),
                ('margin_left_in', models.DecimalField(decimal_places=4, help_text='Sheet edge to the left edge of the first column.', max_digits=6)),
                ('margin_top_in', models.DecimalField(decimal_places=4, help_text='Sheet edge to the top edge of the first row.', max_digits=6)),
                ('pitch_x_in', models.DecimalField(decimal_places=4, help_text='Left edge of one column to the left edge of the next (label width + the gap, not the gap on its own).', max_digits=6)),
                ('pitch_y_in', models.DecimalField(decimal_places=4, help_text='Top edge of one row to the top edge of the next.', max_digits=6)),
                ('x_offset_mm', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Nudge every label right (+) or left (−) to correct this printer's registration. Print the calibration sheet first.", max_digits=5)),
                ('y_offset_mm', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Nudge every label up (+) or down (−).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_stocks, unseed_stocks),
    ]
