# Generated by Django 5.0.6 on 2026-08-19 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0014_labelstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The photo as sent, downscaled on the way in.', upload_to='booth/')),
                ('reason', models.CharField(choices=[('share', 'Something to share'), ('unidentified', 'A scarf nobody could identify')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_website', models.BooleanField(default=False)),
                ('share_instagram', models.BooleanField(default=False)),
                ('people_in_photo', models.BooleanField(default=False, help_text='Someone recognisable is in the shot.')),
                ('people_agreed', models.BooleanField(default=False, help_text="They were asked and said yes. Separate from the ticks above because those record the *sender's* permission, and the sender cannot give permission on behalf of the person in the picture.")),
                ('caption', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, help_text='Anyone to tag, as the sender wrote it.', max_length=200)),
                ('sold_at', models.DateTimeField(blank=True, help_text='When the scarf sold, as reported. Defaults to the moment the photo was sent, which is usually within a minute of it.', null=True)),
                ('sku_prefix', models.CharField(blank=True, help_text="First six characters of the barcode — the blank, not the colorway (SKUs are BLANK-DYEBATH). Nobody can read a colorway off a scarf they couldn't name, but the style is on the tag and it narrows a few hundred products to a few dozen.", max_length=6)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(help_text="Who sent it. PROTECT because a permission with nobody attached to it can't be relied on later.", on_delete=django.db.models.deletion.PROTECT, related_name='booth_photos', to='scarves.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('line_uid', models.CharField(help_text="Square's per-line identifier within the order.", max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('variation_name', models.CharField(blank=True, max_length=255)),
                ('square_variation_id', models.CharField(blank=True, help_text='Blank when the line had no catalog object at all — a custom amount rather than an item.', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.IntegerField(default=0, help_text='What it sold for, in cents. Kept because price is often the strongest hint about which style it was.')),
                ('sold_at', models.DateTimeField(help_text="Square's time for the order, not the time we heard about it.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.CharField(blank=True, max_length=200)),
                ('resolved_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_sales', to='scarves.boothphoto')),
                ('resolved_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_matches', to='scarves.finishedproduct')),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='unmatchedsale',
            constraint=models.UniqueConstraint(fields=('order_id', 'line_uid'), name='one_unmatched_row_per_order_line'),
        ),
    ]
