# Generated by Django 5.0.6 on 2026-08-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0015_boothphoto_unmatchedsale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproductimage',
            name='square_image_id',
            field=models.CharField(blank=True, help_text="Square's ID for this photo once `sync_to_square --images` has pushed it. Blank means Square has never seen it. This is what stops a second run stacking the same photo on the variation again — Square appends to `image_ids` and has no idea it is looking at a picture it already holds.", max_length=100),
        ),
    ]
