# Generated by Django 5.0.6 on 2026-08-20 23:29

import django.db.models.deletion
import scarves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0016_finishedproductimage_square_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=scarves.models.new_run_token, help_text="Path segment for the crew's return URL. Printed as a QR code.", max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the crew first reported back. Null means this sheet is still out — which has to be visible, because a session nobody reported looks exactly like a session that never happened.', null=True)),
                ('included_overshoot', models.BooleanField(default=False, help_text='Whether the sheet included products a whole bath would take past par. See FinishedProduct.behind_a_bath for the distinction.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='scarves.rawproductcategory')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Whoever reported back, if their phone remembered them. A record, not a check: the token on the paper is what lets the report through, so asking for a PIN here would only add friction to a page reached by scanning a sheet you are already holding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='scarves.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRunRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Position on the printed sheet, so the phone lists them in the same order.')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Units this bath yields, as printed on the sheet.')),
                ('done_at', models.DateTimeField(blank=True, help_text="When this bath was reported done. Null means it wasn't.", null=True)),
                ('applied_log', models.ForeignKey(blank=True, help_text='The stock movement this row caused. Set once and then never again — it is what stops a second submission, a double-tapped button or a re-scanned QR from dyeing the same bath twice on paper. Same failure the Square webhook had with redelivered orders, and the same fix.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scarves.inventorylog')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_rows', to='scarves.finishedproduct')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='scarves.productionrun')),
            ],
            options={
                'ordering': ['run', 'order', 'pk'],
            },
        ),
    ]
