# Generated by Django 5.0.6 on 2026-08-20 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0017_productionrun_productionrunrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text="The login this person uses, for the few who have one. Almost nobody does — the crew are deliberately account-less. It exists so a signed-in staff member isn't asked to pick their own name off a list and type a PIN on a page they have already authenticated for. Blank is the normal case and changes nothing.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
