# Generated by Django 5.0.6 on 2026-08-21 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0018_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='recipe',
            field=models.ForeignKey(blank=True, help_text="The colorway. **Null means this was never dyed** — an undyed passthrough, bought and sold as it arrives. Null rather than a sentinel 'Undyed' recipe on purpose: every dyed-only query in the app joins through this FK, so a null row drops out of production planning, the rainbow sheets, the colour pages and the games by construction. A sentinel would need each of those to remember to exclude it, and a forgotten exclusion is silent — an undyed skein filed under a colour it doesn't have.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='scarves.recipe'),
        ),
        migrations.CreateModel(
            name='CatalogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The Square item name, e.g. 'Undyed Yarn'.", max_length=150, unique=True)),
                ('square_item_id', models.CharField(blank=True, help_text="Square CatalogItem ID for the group's item.", max_length=100)),
                ('category', models.ForeignKey(help_text="Square category for the group's item.", on_delete=django.db.models.deletion.PROTECT, related_name='catalog_groups', to='scarves.rawproductcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='catalog_group',
            field=models.ForeignKey(blank=True, help_text="Sell this under a shared Square item instead of one of its own. Blank for everything dyed, which is the normal case — see CatalogGroup for when it isn't.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_products', to='scarves.cataloggroup'),
        ),
    ]
