# Generated by Django 5.0.6 on 2026-08-21 02:53

import scarves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0019_alter_finishedproduct_recipe_cataloggroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrun',
            name='token',
            field=models.CharField(default=scarves.models.new_run_token, help_text="The sheet's code. Rides in the crew's return URL, prints as a QR code, and prints in plain text for someone to type when the QR won't read.", max_length=32, unique=True),
        ),
    ]
