# Generated by Django 5.0.6 on 2026-08-22 23:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0020_alter_productionrun_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dye',
            name='hex_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
    ]
