# Generated by Django 5.0.6 on 2026-08-24 19:25

import django.db.models.deletion
import scarves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0021_alter_dye_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='source',
            field=models.CharField(blank=True, choices=[('production_sheet', 'Production sheet'), ('production_needed', 'Production-needed page'), ('recipe_page', 'Recipe page'), ('card_backfill', 'Kanban card backfill'), ('bulk_update', 'Bulk inventory update'), ('sunday_close', 'Sunday close'), ('square_webhook', 'Square webhook'), ('square_import', 'Square sales import'), ('unmatched_sale', 'Unidentified sale, resolved'), ('test', 'Simulated (fake_sale)')], db_index=True, help_text='Which flow wrote this row. Blank means it predates the field — not that nobody knows, since the notes usually say. Left blank rather than back-filled by pattern-matching those notes, because a guessed provenance counts identically to a recorded one and there is nothing on the row to say which it was.', max_length=30),
        ),
        migrations.CreateModel(
            name='CloseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text="The day this close covers. Unique, because a second run for the same evening is the same evening — two rows would split one session's findings across both and make either one readable as the whole night's work.", unique=True)),
                ('token', models.CharField(default=scarves.models.new_run_token, help_text="This close's code, in the URL. The PIN is checked once, when the day's run is opened; the token is what carries the steps after it, so packing up doesn't mean typing four digits four times.", max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, help_text="Whoever's PIN opened the day's close.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_runs', to='scarves.employee')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='CloseRunRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('pending', 'Not answered yet'), ('confirmed', 'Tag in hand — agrees'), ('missing', 'No tag — app undercounts'), ('extra', 'Tag not predicted — app overcounts')], default='pending', max_length=20)),
                ('on_hand_before', models.PositiveIntegerField(help_text='What the app believed when this row was made. Frozen for the same reason a production row freezes its bath size: it is what the disagreement was measured against, and re-reading it later reads back the number this close already corrected.')),
                ('counted', models.PositiveIntegerField(blank=True, help_text="The bag's actual count. Only a missing tag asks for one.", null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_log', models.ForeignKey(blank=True, help_text='The adjustment this row caused, if it caused one. Set once and never again — the page is reopened, the button is double-tapped, and somebody who remembers one more tag comes back to it. Same failure as a redelivered Square order, same fix.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scarves.inventorylog')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_rows', to='scarves.finishedproduct')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='scarves.closerun')),
            ],
            options={
                'ordering': ['run', 'finished_product__sku', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='closerunrow',
            constraint=models.UniqueConstraint(fields=('run', 'finished_product'), name='one_close_row_per_product'),
        ),
    ]
