# Generated by Django 5.0.6 on 2026-08-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0022_inventorylog_source_closerun_closerunrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pass_pdf',
            field=models.FileField(blank=True, help_text="This person's faire pass, as the PDF that gets handed out. It is served by `secret/handbook/` once they have read the page, which is the only reason the handbook has a name and a PIN on it at all — not to guard the pass, but to know whose to hand over. Blank tells them to contact Michael rather than showing a dead button.", upload_to='crew_passes/'),
        ),
    ]
