# Generated by Django 5.0.6 on 2026-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0023_employee_pass_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothphoto',
            name='reason',
            field=models.CharField(choices=[('share', 'Something to share'), ('unidentified', 'A colorway nobody could identify')], max_length=20),
        ),
    ]
