# Generated by Django 5.0.6 on 2026-08-25 02:36

import django.db.models.deletion
"""The display map, and restocking it.

A fixture is a grid of pegs; a position is one peg and says what lives on it,
or that the space is signage rather than a home. `RestockPass` records a walk
down the board — a repeatable promise that the display was filled — and
`RestockCheck` is one peg's answer.

Nothing here reaches production. Display capacity is a ceiling on what the
board can absorb, never a reason to dye more; see the northstar in CLAUDE.md.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0025_display_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('rows', models.PositiveIntegerField(default=7)),
                ('columns', models.PositiveIntegerField(default=6)),
                ('capacity_per_position', models.PositiveIntegerField(default=2, help_text='How many units one peg or spot holds. Two-skein hooks today. Capacity, never a production target.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='source',
            field=models.CharField(blank=True, choices=[('production_sheet', 'Production sheet'), ('production_needed', 'Production-needed page'), ('recipe_page', 'Recipe page'), ('card_backfill', 'Kanban card backfill'), ('bulk_update', 'Bulk inventory update'), ('sunday_close', 'Sunday close'), ('restock', 'Restocking the display'), ('square_webhook', 'Square webhook'), ('square_import', 'Square sales import'), ('unmatched_sale', 'Unidentified sale, resolved'), ('test', 'Simulated (fake_sale)')], db_index=True, help_text='Which flow wrote this row. Blank means it predates the field — not that nobody knows, since the notes usually say. Left blank rather than back-filled by pattern-matching those notes, because a guessed provenance counts identically to a recorded one and there is nothing on the row to say which it was.', max_length=30),
        ),
        migrations.CreateModel(
            name='DisplayPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('reserved_label', models.CharField(blank=True, help_text="Set when this space isn't a home — 'Price tag', signage. Blank means a real peg. A reserved position is never restocked, never counted, and never contributes display capacity.", max_length=60)),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_positions', to='scarves.finishedproduct')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='scarves.displayfixture')),
            ],
            options={
                'ordering': ['fixture', 'row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='RestockPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Whose PIN signed the promise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_passes', to='scarves.employee')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_passes', to='scarves.displayfixture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('as_predicted', 'As predicted — filled as far as the app said it could'), ('short', "Couldn't fill it — the app was over"), ('over', 'Filled it anyway — the app was under')], default='as_predicted', max_length=20)),
                ('expected', models.PositiveIntegerField(help_text='What the app said could go on this peg — `min(stock, capacity)`, frozen. A peg the app knew was empty expects zero, and confirming that is a completed job rather than a failure.')),
                ('counted', models.PositiveIntegerField(blank=True, help_text="The product's true total. Only an exception asks for one.", null=True)),
                ('applied_log', models.ForeignKey(blank=True, help_text='The adjustment this check caused, if it caused one. Set once — the page gets reopened and the button gets double-tapped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scarves.inventorylog')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_checks', to='scarves.finishedproduct')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='scarves.displayposition')),
                ('restock_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='scarves.restockpass')),
            ],
            options={
                'ordering': ['restock_pass', 'row', 'column'],
            },
        ),
        migrations.AddConstraint(
            model_name='displayposition',
            constraint=models.UniqueConstraint(fields=('fixture', 'row', 'column'), name='one_thing_per_display_position'),
        ),
        migrations.AddConstraint(
            model_name='restockcheck',
            constraint=models.UniqueConstraint(fields=('restock_pass', 'row', 'column'), name='one_restock_check_per_peg'),
        ),
    ]
