# Generated by Django 5.0.6 on 2026-08-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0026_display_map_and_restock'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockpass',
            name='is_full',
            field=models.BooleanField(default=False, help_text="Every peg on the board was answered in this pass. Expected at open and at close, and worth naming because of what it buys: afterwards *every* position has a fresh baseline, so everything the board predicts is trustworthy. After a partial pass some of it isn't.\n\nFrozen rather than derived, because the board gets colorways hung on it and a pass that covered everything at the time must keep saying so.\n\nThis recognises completeness; nothing anywhere penalises the lack of it. A pass covering nine pegs is a completed piece of work, not a failed full check."),
        ),
    ]
