# Generated by Django 5.0.6 on 2026-08-25 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0027_restock_pass_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayfixture',
            name='raw_product',
            field=models.ForeignKey(blank=True, help_text="The blank this board is for. In the shop a board tends to carry one product in all its colorways, and naming it here is what lets the board say which of that blank's colorways aren't up anywhere — the only gap worth fussing about, and one a global list can't express.\n\n**A lens, not a rule.** It never restricts what can be hung: a board that ends up carrying a stray from another blank is a thing that happens on a stall, and an app that refused it would be arguing with the shelf. Blank means a mixed board, which simply has no such report.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_fixtures', to='scarves.rawproduct'),
        ),
    ]
