# Generated by Django 5.0.6 on 2026-08-25 04:49

"""Fancy is a blank, not a flag.

`is_fancy` was a boolean on the product and it could not carry the thing that
actually differs: the price. Extra line work costs more and is what makes the
sale, so "fancy" needs its own `RawProduct` — its own price, its own SKU
prefix, its own Square item and its own board — which is what `Fancy Veil`
already is.

Leaving both in place invited the flag to quietly become a *design*
dimension, and designs are unbounded: a few patterns times a few accent
colours times forty colorways is not a catalogue anybody can enumerate. The
axis stays blank × colorway; which pattern is stitched on a given scarf is a
property of that object, not of the catalogue. If designs must differ in
price, add a tier as another blank (Extra Fancy Veil) — finite, and chosen.

Nothing read it: one template line and the sample-data command. No row in the
shop had it set.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0028_display_fixture_raw_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproduct',
            name='is_fancy',
        ),
    ]
