# Generated by Django 5.0.6 on 2026-08-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0029_drop_is_fancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='made_in_a_dye_bath',
            field=models.BooleanField(default=True, help_text="Uncheck for anything a dye bath cannot produce, and it drops off every production list.\n\nThe case this exists for is the fancy veils. A fancy veil is an already-dyed scarf with extra line work added — so it *has* a colorway and passes every dyed-only query in the app, but you can never answer a shortage of one by dyeing. Sending somebody to the dye room for it is asking for a thing that isn't made there.\n\nUndyed passthroughs are excluded by their null recipe instead and don't need this — see FinishedProduct.recipe. Two markers because they are two different claims: a passthrough was never dyed at all, a fancy veil was dyed and then worked on."),
        ),
    ]
