# Generated by Django 5.0.6 on 2026-08-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0030_made_in_a_dye_bath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='source',
            field=models.CharField(blank=True, choices=[('production_sheet', 'Production sheet'), ('production_needed', 'Production-needed page'), ('recipe_page', 'Recipe page'), ('card_backfill', 'Kanban card backfill'), ('bulk_update', 'Bulk inventory update'), ('sunday_close', 'Sunday close'), ('restock', 'Restocking the display'), ('fancy_conversion', 'Converted to fancy'), ('square_webhook', 'Square webhook'), ('square_import', 'Square sales import'), ('unmatched_sale', 'Unidentified sale, resolved'), ('test', 'Simulated (fake_sale)')], db_index=True, help_text='Which flow wrote this row. Blank means it predates the field — not that nobody knows, since the notes usually say. Left blank rather than back-filled by pattern-matching those notes, because a guessed provenance counts identically to a recorded one and there is nothing on the row to say which it was.', max_length=30),
        ),
    ]
