# Generated by Django 5.0.6 on 2026-09-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0032_rainbow_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The event, stable across years — what a season-over-season comparison groups on.')),
                ('year', models.PositiveIntegerField(help_text='The calendar year this instance of it falls in.')),
                ('name', models.CharField(blank=True, help_text='Optional label. Blank reads as the slug and the year.', max_length=120)),
                ('rule', models.CharField(choices=[('labor_day', 'Labor Day run — nine weekends, generated'), ('manual', 'Dates entered by hand')], default='labor_day', help_text="How this faire's days are known. A generated rule can be re-run for any year; a manual one has its dates entered, and `generate_faire` refuses it rather than inventing a pattern.", max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='FaireDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weekend', models.PositiveSmallIntegerField(help_text='Which weekend of the run, 1-based.')),
                ('is_labor_day', models.BooleanField(default=False, help_text='The Monday. It always lands in weekend 2, which is why that weekend has three trading days and every per-weekend total for it reads about a third high.')),
                ('traded', models.BooleanField(default=True, help_text="Untick for a day the faire did not open. Three days in twenty-two years — a washed-out weekend in 2023 and one hurricane — so there is deliberately no workflow around this, just this checkbox. It matters because it is the denominator: counting 2023's washout as two traded days moves that season's per-day figure by nearly 12%.")),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text="Square's Transaction ID, which is the order id.", max_length=100, unique=True)),
                ('sold_at', models.DateTimeField(db_index=True, help_text='When Square says it happened, never when we imported it.')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('device', models.CharField(blank=True, max_length=120)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('card_brand', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(choices=[('square_csv', 'Square itemised CSV export'), ('square_api', 'Square Orders API'), ('app', "This app's own records")], db_index=True, help_text="Which pipeline supplied this row. Square is today's writer, not the schema — when this app's own records take over, that is one new writer and no new reports, because nothing downstream branches on this. It is printed as a breakdown, the way `InventoryLog.source` already is, never used as a filter that changes what a total means.", max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_key', models.CharField(help_text='Item, price point and an occurrence counter — what makes this line unique inside its order, and what re-importing the same export matches on.', max_length=300)),
                ('sold_at', models.DateTimeField(db_index=True, help_text='Copied from the order so hour-of-day queries need no join.')),
                ('event_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], db_index=True, default='payment', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, help_text="Square's category. Load-bearing for season-over-season totals: the wax hands were on this till through 2024 and are gone now, so a total that does not name its categories reads a discontinued line as a decline.", max_length=120)),
                ('item_name', models.CharField(db_index=True, max_length=255)),
                ('price_point', models.CharField(blank=True, help_text="The colorway, where one was rung up. 'Regular Price' means none was.", max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gross_cents', models.IntegerField(default=0)),
                ('discount_cents', models.IntegerField(default=0)),
                ('net_cents', models.IntegerField(default=0)),
                ('tax_cents', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('square_csv', 'Square itemised CSV export'), ('square_api', 'Square Orders API'), ('app', "This app's own records")], db_index=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-sold_at', 'item_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='faire',
            constraint=models.UniqueConstraint(fields=('slug', 'year'), name='one_faire_per_event_per_year'),
        ),
        migrations.AddField(
            model_name='faireday',
            name='faire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='scarves.faire'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='scarves.finishedproduct'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='raw_product',
            field=models.ForeignKey(blank=True, help_text='The blank, matched off the item name. Coarser than the SKU and available for every season.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='scarves.rawproduct'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scarves.sale'),
        ),
        migrations.AddConstraint(
            model_name='faireday',
            constraint=models.UniqueConstraint(fields=('faire', 'date'), name='one_faire_day_per_date'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.UniqueConstraint(fields=('sale', 'line_key'), name='one_sale_line_per_key'),
        ),
    ]
