# Generated by Django 5.0.6 on 2026-09-02 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0033_sales_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='faire',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Where the faire is, for the weather fetch. Roughly is fine — the archive grid is about nine kilometres.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='faire',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='DayWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('low_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mean_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('precipitation_in', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cloud_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Mean cloud cover over opening hours, not over the whole day. Fog at four in the morning is not weather anybody stood in.', max_digits=5, null=True)),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Mean relative humidity over opening hours.', max_digits=5, null=True)),
                ('source', models.CharField(default='open-meteo', help_text='Where the reading came from, so a re-sourced season is visible.', max_length=60)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='scarves.faireday')),
            ],
            options={
                'verbose_name_plural': 'day weather',
                'ordering': ['day__date'],
            },
        ),
    ]
