# Generated by Django 5.0.6 on 2026-09-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0034_day_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='square_variation_id',
            field=models.CharField(blank=True, db_index=True, help_text="Square's own id for the variation sold, where the source carried one — the Orders API does, the CSV export does not. Kept because it is the only durable handle on a line: item names get edited and catalogue objects get deleted, and this is what lets a category be resolved again later without re-fetching every order.", max_length=100),
        ),
    ]
