"""Routing a bath's output to fancy at the moment it is made.

A fancy veil is an already-dyed scarf with extra line work. Until now the only
record of one was a *conversion* — plain stock down, fancy stock up, recorded
afterwards by somebody who remembered. That leaves the plain side overstated
until it is noticed, and it makes fancy supply answerable only by inference.

Deciding it at production instead costs almost nothing and is better evidence:
the person who made the bath says four plain and one fancy, and the fancy one
is never counted as plain at all.

Two fields:

- `RawProduct.fancy_counterpart` — one to one, set on the plain blank. A half
  circle veil becomes a fancy half circle veil and nothing else, so there is
  no question to ask at reporting time. Null for every yarn and most silk,
  which is what keeps fancy a silk-only concern with nothing checking for
  silk — a category test would break the day a fancy shawl exists.
- `ProductionRunRow.fancy_yield` — how many of `yielded` were finished fancy.
  A subset, never an addition, so `loss` keeps meaning what it says.

Nothing is backfilled and nothing needs to be: no counterpart is set yet, so
every existing row keeps a null `fancy_yield` and behaves exactly as before.
The conversion page is unchanged and stays the record of the other route.
"""

# Generated by Django 5.0.6 on 2026-09-08 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0036_production_row_end_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrunrow',
            name='fancy_yield',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many of `yielded` were finished as fancy rather than plain. A subset, never an addition: five came out of a bath of five and one of them is fancy, so `yielded` is 5 and this is 1.\n\nRecorded here as well as in the ledger because this is the only place that says a fancy veil was made *as* one. The conversion page answers the other route — a plain scarf that had line work added later — and a question about fancy supply has to read both.', null=True),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='fancy_counterpart',
            field=models.ForeignKey(blank=True, help_text="The fancy version of this blank, if it has one. A half circle veil becomes a fancy half circle veil and nothing else — the pairing is one to one, because a veil cannot become a fancy shawl.\n\nSet on the *plain* blank, pointing at the fancy one. What it buys is routing at production time: a bath of five can be reported as four plain and one fancy, so a fancy veil is recorded as it is made rather than reconstructed later from a conversion.\n\nBlank means this has no fancy version, which is every yarn and most silk. That is what keeps fancy a silk-only concern without anything having to check for silk — a category test would break the day a fancy shawl exists, the same way it would have for 'made in a dye bath'.", limit_choices_to={'made_in_a_dye_bath': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plain_counterparts', to='scarves.rawproduct'),
        ),
    ]
