# Generated by Django 5.0.6 on 2026-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0037_fancy_at_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='oven',
            field=models.BooleanField(default=False, help_text="Whether this sheet is an oven run. Recorded rather than re-derived, for the reason the category and the bath sizes are: a reprint has to say what the paper said, and 'were these all oven colorways at the time?' has exactly one honest answer, which is what was written down.\n\nIt also decides what the run page will let somebody add. The oven holds `production.OVEN_TRAYS` trays and nothing else fits in it, so a stovetop colorway appended to an oven sheet is a bath that cannot be run where the paper says to run it."),
        ),
        migrations.AddField(
            model_name='recipe',
            name='oven_dyed',
            field=models.BooleanField(db_index=True, default=False, help_text='Tick for a colorway that is made in the oven rather than in a pot, and it moves from one kind of session to the other.\n\nThis is a property of the colour, not of the yarn: the technique is what produces the result, so an oven colorway is oven-dyed on every blank it is dyed on.\n\n**It partitions both ways, which is the whole point.** An oven colorway is the only thing that can go on an oven run, and it must also drop off the ordinary dye-room sheet — otherwise somebody is sent to a sink to make a thing that is not made there. That is the same failure `RawProduct.made_in_a_dye_bath` exists to stop, one technique further in.\n\n`private/production-needed/` deliberately does *not* filter on this. It reports what is below par, and an oven colorway being short is a real fact worth reading; it badges the row instead, so the reason it is missing from the dye-room sheet is visible rather than silent.'),
        ),
    ]
