# Generated by Django 5.0.6 on 2026-09-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0038_productionrun_oven_recipe_oven_dyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text="When somebody killed this sheet's printed code. The paper still says what it says and this app cannot reach into a dye room to change that, so revoking is how a code that got out stops working.\n\n**Revoked, not rotated.** Issuing a new token would leave the paper pointing at nothing and take the trail from the sheet to the run with it — the token is how a printed sheet and a record are the same thing. Setting this keeps every word of that and only refuses the door.\n\nIt closes the no-login door and nothing else: the staff page at private/production-sheet/<pk>/ still accepts and cancels baths, so a session in progress is interrupted rather than lost. Reprint to hand the crew a working code.", null=True),
        ),
    ]
