# Generated by Django 5.0.6 on 2026-09-10 02:47

import scarves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0039_production_run_revoked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrun',
            name='token',
            field=models.CharField(default=scarves.models.new_run_token, help_text="The sheet's code. Rides in the crew's return URL, prints as a QR code, and prints in plain text for someone to type when the QR won't read.\n\n**Editable, and changing it orphans the paper** — every printed copy of this sheet keeps pointing at the old code, which will then resolve to nothing. That is the point when a code has got out and you want it dead. When somebody may still be holding the sheet, prefer Revoke: it shuts the same door and the crew's page says so, where a rewritten token leaves them hunting for a character they think they mistyped.", max_length=32, unique=True),
        ),
    ]
