# Generated by Django 5.0.6 on 2026-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0040_token_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='counted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When somebody last physically counted this shelf.\n\nOnly an absolute count sets it. A delivery received does not: the raw-inventory page already draws that line — a count is a measurement and a delivery note is a claim about a change — and this is the same distinction with a date on it.\n\nIt exists because raw stock is the one pile nothing recounts on its own. The finished side heals: a restock walk and the Sunday close both put an absolute count against what the app believed. Undyed yarn has no equivalent, and it only ever goes down when somebody records a dye bath — so a week of dyeing that has not been entered yet leaves this number too high, with nothing anywhere saying so. Ordering against a stale count under-buys exactly when the dye room has been busiest.', null=True),
        ),
    ]
