# Generated by Django 5.0.6 on 2026-09-14 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0043_production_from_a_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='fancying_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What it costs to turn one plain blank into this fancy one — the line work, and nothing else. Set this on the *fancy* blank; leave it empty on everything you buy.\n\nIt exists so a fancy blank's cost has exactly one home. `price` is what a supplier charges, and a fancy veil has no supplier: it is a plain veil somebody worked on. Storing its whole cost in `price` meant the same silk was priced in two rows, so a supplier increase landed on the plain one and the fancy one quietly kept last year's number — which is how the three fancy blanks drifted $8.96, $13.78 and $17.30 away from plain-plus-fancying, each by a different amount and none of them wrong anywhere you could see it.\n\nRead `blank_cost`, never `price`, for what a blank costs.", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
