# Generated by Django 5.0.6 on 2026-09-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """Freeze what a bath cost and made, at the moment it is accepted.

    Nothing backfills. Rows accepted before this land null, and null is not
    zero: today's prices are not the prices that applied then, and filling
    them in would invent exactly the number these columns exist to pin down.
    `dyebill` counts those baths and leaves them unvalued.
    """


    dependencies = [
        ('scarves', '0045_fancying_cost_moves_off_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrunrow',
            name='output_retail',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text="The whole bath's output at the asking price when it was accepted — plain units at their price and any fancy ones at theirs, which is why this is a total where the cost beside it is a unit price.\n\nA total because the two halves of a split bath sell for different money, so no single unit price describes what came out. Blanks are the other way round: a bath eats `quantity` of one blank at one cost, however its output was finished.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionrunrow',
            name='unit_blank_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='What one blank cost when this bath was accepted. Frozen at that moment, like `quantity` is frozen when the sheet prints, and for a stronger version of the same reason: this is what a bill for the session is drawn from, and a bill has to be against the prices at the time. Derived on read, a supplier increase would silently rewrite what every past session was worth.\n\nNull means the row was accepted before the figures were kept, which is not zero — a statement reports those rows as unpriced rather than free.', max_digits=8, null=True),
        ),
    ]
