# Generated by Django 5.0.6 on 2026-09-16 01:25

from django.db import migrations, models


def set_the_yarn_basis(apps, schema_editor):
    """Yarn's dye-book bath is five skeins. Say so, once, here.

    Without this the column is null everywhere and the feature is silently
    off — every amount typed in would be stored and none would ever print,
    which looks exactly like the arithmetic being broken. Matching the
    category by name belongs in a migration and nowhere else, for the reason
    0047 gives: it applies a fact to the rows as they stand, where the app
    goes on reading the field.

    Silk is deliberately left null. The ounces on a recipe are the book's
    yarn numbers; what a silk scarf drinks is a question nobody has answered,
    and a basis here would answer it by arithmetic.
    """
    RawProductCategory = apps.get_model("scarves", "RawProductCategory")
    RawProductCategory.objects.filter(name="Yarn").update(dye_book_bath_units=5)


def clear_the_yarn_basis(apps, schema_editor):
    RawProductCategory = apps.get_model("scarves", "RawProductCategory")
    RawProductCategory.objects.filter(name="Yarn").update(dye_book_bath_units=None)


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0047_oven_moves_to_the_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproductcategory',
            name='dye_book_bath_units',
            field=models.PositiveSmallIntegerField(blank=True, help_text="How many units one dye-book bath covers on this table. Yarn is 5 — the book writes every amount for a five-skein bath, so a four-skein bath takes 80% of what is written. **Null means the book has no figures for this fibre**, and no amount is printed for it. Silk is null on purpose: the ounces on a recipe are the book's yarn numbers, and what a silk scarf drinks is a different question nobody has answered. Setting a basis on a second category claims those same numbers apply there, which is the one way to get this wrong quietly — the sheet would print a confident amount off the wrong fibre.", null=True),
        ),
        migrations.AddField(
            model_name='recipedye',
            name='book_ounces',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Ounces of this dye, exactly as the dye book writes it: the amount for one full bath of the category that carries a `dye_book_bath_units` basis (yarn, five skeins). Stored as written rather than per skein because that is what somebody is copying off the page, and a number typed in the form it is read in can be checked against the book by eye.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipedye',
            name='ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional proportion (e.g. % of total). Not the dye-book amount — that is `book_ounces`, which is an absolute weight.', max_digits=5, null=True),
        ),
        migrations.RunPython(set_the_yarn_basis, clear_the_yarn_basis),
    ]
