# Generated by Django 5.0.6 on 2026-09-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    """The scale reads tenths, so the box stores tenths.

    Narrowing, so Postgres rounds anything already on file — which is nothing
    worth keeping: the column shipped hours ago and the dye book has not been
    typed in yet. Widening it back is the reversal, and a rounded figure does
    not come back with it.
    """


    dependencies = [
        ('scarves', '0048_dye_amounts_per_bath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedye',
            name='book_ounces',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ounces of this dye, exactly as the dye book writes it: the amount for one full bath of the category that carries a `dye_book_bath_units` basis (yarn, five skeins). Stored as written rather than per skein because that is what somebody is copying off the page, and a number typed in the form it is read in can be checked against the book by eye. One decimal place, because that is what the scale reads — a box offering hundredths invites a figure nobody can weigh out.', max_digits=5, null=True),
        ),
    ]
