# Generated by Django 5.0.6 on 2026-09-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0050_hours_say_what_kind_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('website', models.URLField(blank=True, help_text="The supplier's own site, when they have one.")),
                ('contact', models.CharField(blank=True, help_text="How to reach them — a name, a phone number, a stall. Free text on purpose: 'Sarah, 555-0143' and 'the pottery stall by the joust field' are both the real answer for somebody here, and a structured contact form would refuse the second one.", max_length=300)),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, help_text='Roughly how long between ordering and having it, in days.\n\n**Null means nobody has said**, and that is different from zero. Nothing computes an order-by date from a null, because a date derived from a guess is exactly the kind of number that reads as a fact — see the par argument in CLAUDE.md.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Anything else about dealing with them.')),
                ('is_active', models.BooleanField(default=True, help_text="Uncheck when you stop buying from them. Retire, don't delete.")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='order_url',
            field=models.URLField(blank=True, help_text="The product page for this exact blank, when there is one. Not the supplier — that is `supplier`, and it is a separate question: this is 'where do I buy this thing', that is 'who from'."),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Who this is bought from. PROTECT rather than SET_NULL: a supplier with blanks pointing at it is one you have bought from, and retiring is how it goes away — the rule the whole catalogue follows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_products', to='scarves.supplier'),
        ),
    ]
