# Generated by Django 5.0.6 on 2026-09-22 00:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0052_backfill_suppliers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text="The supplier's order or invoice number, normalised to upper case. Required to book, because it is what makes booking the same delivery twice visible instead of silent.", max_length=60)),
                ('ordered_on', models.DateField(blank=True, help_text="The date on the document. Null means nobody could read one — not today's date, which would be a guess wearing a fact's clothes.", null=True)),
                ('document', models.FileField(blank=True, help_text='The PDF or photograph this was read from, kept so the cost on a blank has a basis somebody can open. Advice you cannot inspect is a decision in disguise.', upload_to='invoices/')),
                ('pasted_text', models.TextField(blank=True, help_text='The text this was read from, when it arrived pasted out of an email rather than as a file. Kept for the same reason the document is: a cost with no basis anybody can open reads as a fact. One of the two is filled in, never both.')),
                ('read_note', models.TextField(blank=True, help_text='What the reader made of the document, or why it made nothing of it. Diagnostic only; nothing reads it back.')),
                ('booked_at', models.DateTimeField(blank=True, help_text='When somebody confirmed it. Null means it is still a draft.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_booked', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Who sent it, when it matches a supplier already on file.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='scarves.supplier')),
            ],
            options={
                'ordering': ['-ordered_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='What the invoice itself called it, kept verbatim. This is the basis for the match beside it — a suggestion whose evidence is hidden is not something anybody can agree or disagree with.', max_length=300)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='How many arrived on this line — the pack.')),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, help_text='What the line came to, before shipping and tax.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='What one costs — this is what gets written onto the blank.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, help_text='What the blank cost before this line was booked.', max_digits=8, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scarves.supplierinvoice')),
                ('raw_product', models.ForeignKey(blank=True, help_text="The blank this line bought.\n\nNull only ever on a draft: it is a line the reader could not match, sitting there as a question for somebody. Booking one is what settles it, and a booked line always names a blank — the page refuses a ticked row that doesn't, by name, rather than quietly dropping it.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='scarves.rawproduct')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
