# Generated by Django 5.0.6 on 2026-09-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0053_read_an_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='invoice_description',
            field=models.CharField(blank=True, editable=False, help_text='What the supplier calls this on their paperwork, in their words.\n\n`Machine Hemmed 8mm Habotai Scarves 21" x 76" Circle` is an Infinity, and there is no way to derive that — not from the name, not from the fibre, not by any amount of reading. It is simply a fact somebody knows. But it only has to be said once, and then it is worth more than a reading: an exact match is a certainty where a model is a suggestion.\n\n**Nothing types this in.** It is written by confirming an invoice line against this blank — the choice somebody was making anyway — which is why it is `editable=False`. Confirming a different wording replaces it, and confirming this wording against a *different* blank takes it off this one, so a mis-match heals the next time somebody gets it right rather than leaving two blanks claiming the same line.', max_length=300),
        ),
    ]
