# Generated by Django 5.0.6 on 2026-09-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0054_remember_what_the_invoice_called_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='received_on',
            field=models.DateField(blank=True, help_text='When the goods actually turned up. **Null means still on order**, and that is the whole of the status this needs.\n\nA date rather than a status field, because every other not-yet-happened in this app is one — a null `booked_at` is a draft, a null `counted_at` is a shelf nobody counted, a null `lead_time_days` is nobody having said. A date answers *when* as well as *whether*, which an enum with two values never can.\n\nIt exists because most of these documents are **order confirmations, not delivery notes**. Booking one used to put the goods on the shelf the moment it was read — and `number_on_hand` is what a production run claims its blanks from, so the dye room could be sent to start baths against yarn still in a van. The cost is knowable at order time and lands then; the stock waits for the box.', null=True),
        ),
    ]
