# Generated by Django 5.0.6 on 2026-09-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0055_an_invoice_is_ordered_then_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='written_off_note',
            field=models.CharField(blank=True, help_text="Why, in whatever words fit — 'never shipped', 'back-ordered to March, cancelled', 'arrived soaked'. Free text because the real answers vary and a fixed list of reasons would collect 'other'.", max_length=200),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='written_off_on',
            field=models.DateField(blank=True, help_text="When it was given up on — lost, undeliverable, cancelled. The other way an order ends.\n\n**It closes the order without moving any stock**, which is the whole of what it does and the reason it cannot be folded into `received_on`: a received date says goods are on a shelf, and putting one here would claim a delivery that never happened. Two mutually exclusive events, each with its own date.\n\nWhat it really undoes is the *suppression*. An open order takes a blank's shortage off the reorder page — see `RawProduct.raw_shortage` — so an order that is never coming would hold that signal down for good, silently, which is the worst shape a bug takes here. This is the door that gives the signal back, and a person walks through it rather than a rule.", null=True),
        ),
    ]
