# Generated by Django 5.0.6 on 2026-09-22 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarves', '0056_an_order_can_also_never_arrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='How many actually turned up, when it is not what was ordered.\n\n**Null means all of it**, which is the ordinary case and why this is nullable rather than a copy of `quantity` written on every line. Ordered 80 and received 50 are both true, so both are kept: `quantity` is what the document says was bought and this is what reached the shelf.\n\nNothing here tracks the refund or the outstanding 30. A short delivery is settled with the supplier by a person; what the app needs is a shelf that matches the room.', null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceline',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the line came to, before shipping and tax — as billed, so it stays true of the document even when less arrives.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
